Default dictionary to English, utf-8 encoding
Previous default dictionary was Spanish, but is more often used English,
the English dictionary is set as ispell-dictionary, run "hunspell -D"
and check AVAILABLE DIRECTORIES, there must be a default dictionary,
with files named default.aff and default.dic.

ERROR: ispell-phaf: No matching entry for nil.